### ISSUE TITLE
Add nuget cache clear button

### ISSUE THREAD

**Issue by mit200** [MiroslavMikus/DependencyScanner#2]

**Comment by MiroslavMikus** [comment]
Do you mean under the packages folder under in the solution root folder?

**Comment by mit200** [comment]
Maybe just a global nuget cach clear here is the command I'm using right now:
`nuget locals all -clear`

**Comment by MiroslavMikus** [comment]
Ok
- button is coming to the solution template
- settings page will become new field -> pick nuget.exe path

**Comment by MiroslavMikus** [comment]
Done. That means -> please test ;)

**Comment by MiroslavMikus** [comment]
Tested, works -> closing issue
