### ISSUE TITLE
Shortcut for nuget cash clear

### ISSUE THREAD

**Issue by mit200** [MiroslavMikus/DependencyScanner#3]
The Nuget Cash clear command is not so easy to access -> would be nice if the application is focused if a shortcur is provided with a tooltip on the clear button

**Comment by MiroslavMikus** [comment]
NP, does this button work at all?

**Comment by MiroslavMikus** [comment]
Please test ctrl+Q

**Comment by MiroslavMikus** [comment]
Tested, works -> closing issue
